# Generated by Django 4.1.7 on 2023-03-05 22:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('description', models.TextField()),
                ('dateCreated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('fmale', 'fmale')], max_length=10, null=True)),
                ('visits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.visit')),
            ],
        ),
    ]
